let
    源 = Odbc.Query("dsn=bytehouse_rl", 
    "
SELECT '2026-07-28 10:00:00' AS etl_time, '2026/7/15' AS dt, 'day' AS data_type, '2026-07-15' AS data_date, '29' AS data_week, 'FW202629' AS data_week_name, '07_Oct' AS data_month, '2026财年7月' AS data_month_name, '3' AS data_quarter, '2026财年第三季度' AS data_quarter_name, '2026' AS data_year, '2026财年' AS data_year_name, 'TM' AS framework, 'MN' AS gender, 'POLO' AS brand, 'APPAREL' AS product_type, 'TOPS' AS category_summary, 'SHIRT' AS category, 'payment' AS calc_type, 'Exclude orders cancelled in pay date' AS fulfillment_calc_type, 'RMB' AS currency, 12 AS o2o_fulfillment_request_failed_times, 150 AS o2o_fulfillment_request_times, 125.50 AS o2o_fulfillment_request_duration, 88 AS o2o_fulfillment_request_sku_qty
UNION ALL
SELECT '2026-07-28 10:00:00' AS etl_time, '2026/7/15' AS dt, 'day' AS data_type, '2026-07-15' AS data_date, '29' AS data_week, 'FW202629' AS data_week_name, '07_Oct' AS data_month, '2026财年7月' AS data_month_name, '3' AS data_quarter, '2026财年第三季度' AS data_quarter_name, '2026' AS data_year, '2026财年' AS data_year_name, 'JD' AS framework, 'CW' AS gender, 'RALPH' AS brand, 'ACCESSORIES' AS product_type, 'BOTTOMS' AS category_summary, 'PANT' AS category, 'payment' AS calc_type, 'Exclude orders cancelled in paydate & EC-fulfilled from O2O unfulfilled' AS fulfillment_calc_type, 'RMB' AS currency, 15 AS o2o_fulfillment_request_failed_times, 185 AS o2o_fulfillment_request_times, 148.30 AS o2o_fulfillment_request_duration, 102 AS o2o_fulfillment_request_sku_qty
UNION ALL
SELECT '2026-07-28 10:00:00' AS etl_time, '2026/7/20' AS dt, 'day' AS data_type, '2026-07-20' AS data_date, '30' AS data_week, 'FW202630' AS data_week_name, '07_Oct' AS data_month, '2026财年7月' AS data_month_name, '3' AS data_quarter, '2026财年第三季度' AS data_quarter_name, '2026' AS data_year, '2026财年' AS data_year_name, 'RLE' AS framework, 'WM' AS gender, 'LAUREN' AS brand, 'FOOTWEAR' AS product_type, 'OUTERWEAR' AS category_summary, 'JACKET' AS category, 'fulfillment' AS calc_type, 'Exclude orders cancelled in pay date' AS fulfillment_calc_type, 'RMB' AS currency, 18 AS o2o_fulfillment_request_failed_times, 210 AS o2o_fulfillment_request_times, 172.60 AS o2o_fulfillment_request_duration, 118 AS o2o_fulfillment_request_sku_qty
UNION ALL
SELECT '2026-07-28 10:00:00' AS etl_time, '2026/7/20' AS dt, 'day' AS data_type, '2026-07-20' AS data_date, '30' AS data_week, 'FW202630' AS data_week_name, '07_Oct' AS data_month, '2026财年7月' AS data_month_name, '3' AS data_quarter, '2026财年第三季度' AS data_quarter_name, '2026' AS data_year, '2026财年' AS data_year_name, 'JD' AS framework, 'WM' AS gender, 'POLO' AS brand, 'APPAREL' AS product_type, 'TOPS' AS category_summary, 'DRESS' AS category, 'fulfillment' AS calc_type, 'Exclude orders cancelled in paydate & EC-fulfilled from O2O unfulfilled' AS fulfillment_calc_type, 'RMB' AS currency, 20 AS o2o_fulfillment_request_failed_times, 235 AS o2o_fulfillment_request_times, 195.40 AS o2o_fulfillment_request_duration, 132 AS o2o_fulfillment_request_sku_qty
UNION ALL
SELECT '2026-07-28 10:00:00' AS etl_time, '2026/7/20' AS dt, 'day' AS data_type, '2026-07-20' AS data_date, '30' AS data_week, 'FW202630' AS data_week_name, '07_Oct' AS data_month, '2026财年7月' AS data_month_name, '3' AS data_quarter, '2026财年第三季度' AS data_quarter_name, '2026' AS data_year, '2026财年' AS data_year_name, 'RLE' AS framework, 'MN' AS gender, 'RALPH' AS brand, 'ACCESSORIES' AS product_type, 'BOTTOMS' AS category_summary, 'COAT' AS category, 'payment' AS calc_type, 'Exclude orders cancelled in pay date' AS fulfillment_calc_type, 'RMB' AS currency, 14 AS o2o_fulfillment_request_failed_times, 175 AS o2o_fulfillment_request_times, 158.20 AS o2o_fulfillment_request_duration, 95 AS o2o_fulfillment_request_sku_qty
UNION ALL
SELECT '2026-07-28 10:00:00' AS etl_time, '2026/6/15' AS dt, 'day' AS data_type, '2026-06-15' AS data_date, '25' AS data_week, 'FW202625' AS data_week_name, '06_Sep' AS data_month, '2026财年6月' AS data_month_name, '3' AS data_quarter, '2026财年第三季度' AS data_quarter_name, '2026' AS data_year, '2026财年' AS data_year_name, 'RLE' AS framework, 'WM' AS gender, 'POLO' AS brand, 'APPAREL' AS product_type, 'TOPS' AS category_summary, 'PANT' AS category, 'fulfillment' AS calc_type, 'Exclude orders cancelled in pay date' AS fulfillment_calc_type, 'RMB' AS currency, 22 AS o2o_fulfillment_request_failed_times, 265 AS o2o_fulfillment_request_times, 218.50 AS o2o_fulfillment_request_duration, 155 AS o2o_fulfillment_request_sku_qty
UNION ALL
SELECT '2026-07-28 10:00:00' AS etl_time, '2026/6/15' AS dt, 'day' AS data_type, '2026-06-15' AS data_date, '25' AS data_week, 'FW202625' AS data_week_name, '06_Sep' AS data_month, '2026财年6月' AS data_month_name, '3' AS data_quarter, '2026财年第三季度' AS data_quarter_name, '2026' AS data_year, '2026财年' AS data_year_name, 'DY' AS framework, 'WM' AS gender, 'RALPH' AS brand, 'ACCESSORIES' AS product_type, 'BOTTOMS' AS category_summary, 'JACKET' AS category, 'fulfillment' AS calc_type, 'Exclude orders cancelled in paydate & EC-fulfilled from O2O unfulfilled' AS fulfillment_calc_type, 'RMB' AS currency, 25 AS o2o_fulfillment_request_failed_times, 295 AS o2o_fulfillment_request_times, 238.70 AS o2o_fulfillment_request_duration, 172 AS o2o_fulfillment_request_sku_qty
UNION ALL
SELECT '2026-07-28 10:00:00' AS etl_time, '2026/6/15' AS dt, 'day' AS data_type, '2026-06-15' AS data_date, '25' AS data_week, 'FW202625' AS data_week_name, '06_Sep' AS data_month, '2026财年6月' AS data_month_name, '3' AS data_quarter, '2026财年第三季度' AS data_quarter_name, '2026' AS data_year, '2026财年' AS data_year_name, 'DY' AS framework, 'MN' AS gender, 'LAUREN' AS brand, 'FOOTWEAR' AS product_type, 'OUTERWEAR' AS category_summary, 'DRESS' AS category, 'payment' AS calc_type, 'Exclude orders cancelled in pay date' AS fulfillment_calc_type, 'RMB' AS currency, 28 AS o2o_fulfillment_request_failed_times, 325 AS o2o_fulfillment_request_times, 258.90 AS o2o_fulfillment_request_duration, 188 AS o2o_fulfillment_request_sku_qty
UNION ALL
SELECT '2026-07-28 10:00:00' AS etl_time, '2026/6/20' AS dt, 'day' AS data_type, '2026-06-20' AS data_date, '25' AS data_week, 'FW202625' AS data_week_name, '06_Sep' AS data_month, '2026财年6月' AS data_month_name, '3' AS data_quarter, '2026财年第三季度' AS data_quarter_name, '2026' AS data_year, '2026财年' AS data_year_name, 'DY' AS framework, 'CW' AS gender, 'POLO' AS brand, 'APPAREL' AS product_type, 'TOPS' AS category_summary, 'COAT' AS category, 'payment' AS calc_type, 'Exclude orders cancelled in paydate & EC-fulfilled from O2O unfulfilled' AS fulfillment_calc_type, 'RMB' AS currency, 30 AS o2o_fulfillment_request_failed_times, 355 AS o2o_fulfillment_request_times, 278.40 AS o2o_fulfillment_request_duration, 205 AS o2o_fulfillment_request_sku_qty
UNION ALL
SELECT '2026-07-28 10:00:00' AS etl_time, '2026/6/20' AS dt, 'day' AS data_type, '2026-06-20' AS data_date, '25' AS data_week, 'FW202625' AS data_week_name, '06_Sep' AS data_month, '2026财年6月' AS data_month_name, '3' AS data_quarter, '2026财年第三季度' AS data_quarter_name, '2026' AS data_year, '2026财年' AS data_year_name, 'DY' AS framework, 'WM' AS gender, 'RALPH' AS brand, 'ACCESSORIES' AS product_type, 'BOTTOMS' AS category_summary, 'SHIRT' AS category, 'fulfillment' AS calc_type, 'Exclude orders cancelled in pay date' AS fulfillment_calc_type, 'RMB' AS currency, 32 AS o2o_fulfillment_request_failed_times, 385 AS o2o_fulfillment_request_times, 298.60 AS o2o_fulfillment_request_duration, 222 AS o2o_fulfillment_request_sku_qty
UNION ALL
SELECT '2026-07-28 10:00:00' AS etl_time, '2026/6/20' AS dt, 'day' AS data_type, '2026-06-20' AS data_date, '25' AS data_week, 'FW202625' AS data_week_name, '06_Sep' AS data_month, '2026财年6月' AS data_month_name, '3' AS data_quarter, '2026财年第三季度' AS data_quarter_name, '2026' AS data_year, '2026财年' AS data_year_name, 'DY' AS framework, 'WM' AS gender, 'LAUREN' AS brand, 'FOOTWEAR' AS product_type, 'OUTERWEAR' AS category_summary, 'PANT' AS category, 'fulfillment' AS calc_type, 'Exclude orders cancelled in paydate & EC-fulfilled from O2O unfulfilled' AS fulfillment_calc_type, 'RMB' AS currency, 35 AS o2o_fulfillment_request_failed_times, 415 AS o2o_fulfillment_request_times, 318.80 AS o2o_fulfillment_request_duration, 238 AS o2o_fulfillment_request_sku_qty
UNION ALL
SELECT '2026-07-28 10:00:00' AS etl_time, '2026/6/20' AS dt, 'day' AS data_type, '2026-06-20' AS data_date, '25' AS data_week, 'FW202625' AS data_week_name, '06_Sep' AS data_month, '2026财年6月' AS data_month_name, '3' AS data_quarter, '2026财年第三季度' AS data_quarter_name, '2026' AS data_year, '2026财年' AS data_year_name, 'DY' AS framework, 'MN' AS gender, 'POLO' AS brand, 'APPAREL' AS product_type, 'TOPS' AS category_summary, 'JACKET' AS category, 'payment' AS calc_type, 'Exclude orders cancelled in pay date' AS fulfillment_calc_type, 'RMB' AS currency, 38 AS o2o_fulfillment_request_failed_times, 445 AS o2o_fulfillment_request_times, 338.50 AS o2o_fulfillment_request_duration, 255 AS o2o_fulfillment_request_sku_qty
UNION ALL
SELECT '2026-07-28 10:00:00' AS etl_time, '2025/7/15' AS dt, 'day' AS data_type, '2025-07-15' AS data_date, '29' AS data_week, 'FW202529' AS data_week_name, '07_Oct' AS data_month, '2025财年7月' AS data_month_name, '3' AS data_quarter, '2025财年第三季度' AS data_quarter_name, '2025' AS data_year, '2025财年' AS data_year_name, 'DY' AS framework, 'MN' AS gender, 'POLO' AS brand, 'APPAREL' AS product_type, 'TOPS' AS category_summary, 'JACKET' AS category, 'payment' AS calc_type, 'Exclude orders cancelled in pay date' AS fulfillment_calc_type, 'RMB' AS currency, 40 AS o2o_fulfillment_request_failed_times, 475 AS o2o_fulfillment_request_times, 358.20 AS o2o_fulfillment_request_duration, 272 AS o2o_fulfillment_request_sku_qty
UNION ALL
SELECT '2026-07-28 10:00:00' AS etl_time, '2025/7/15' AS dt, 'day' AS data_type, '2025-07-15' AS data_date, '29' AS data_week, 'FW202529' AS data_week_name, '07_Oct' AS data_month, '2025财年7月' AS data_month_name, '3' AS data_quarter, '2025财年第三季度' AS data_quarter_name, '2025' AS data_year, '2025财年' AS data_year_name, 'DY' AS framework, 'CW' AS gender, 'RALPH' AS brand, 'ACCESSORIES' AS product_type, 'BOTTOMS' AS category_summary, 'DRESS' AS category, 'payment' AS calc_type, 'Exclude orders cancelled in paydate & EC-fulfilled from O2O unfulfilled' AS fulfillment_calc_type, 'RMB' AS currency, 42 AS o2o_fulfillment_request_failed_times, 505 AS o2o_fulfillment_request_times, 378.90 AS o2o_fulfillment_request_duration, 288 AS o2o_fulfillment_request_sku_qty
UNION ALL
SELECT '2026-07-28 10:00:00' AS etl_time, '2025/7/15' AS dt, 'day' AS data_type, '2025-07-15' AS data_date, '29' AS data_week, 'FW202529' AS data_week_name, '07_Oct' AS data_month, '2025财年7月' AS data_month_name, '3' AS data_quarter, '2025财年第三季度' AS data_quarter_name, '2025' AS data_year, '2025财年' AS data_year_name, 'TM' AS framework, 'WM' AS gender, 'LAUREN' AS brand, 'FOOTWEAR' AS product_type, 'OUTERWEAR' AS category_summary, 'COAT' AS category, 'fulfillment' AS calc_type, 'Exclude orders cancelled in pay date' AS fulfillment_calc_type, 'RMB' AS currency, 45 AS o2o_fulfillment_request_failed_times, 535 AS o2o_fulfillment_request_times, 398.40 AS o2o_fulfillment_request_duration, 305 AS o2o_fulfillment_request_sku_qty
UNION ALL
SELECT '2026-07-28 10:00:00' AS etl_time, '2025/7/20' AS dt, 'day' AS data_type, '2025-07-20' AS data_date, '30' AS data_week, 'FW202530' AS data_week_name, '07_Oct' AS data_month, '2025财年7月' AS data_month_name, '3' AS data_quarter, '2025财年第三季度' AS data_quarter_name, '2025' AS data_year, '2025财年' AS data_year_name, 'DY' AS framework, 'WM' AS gender, 'POLO' AS brand, 'APPAREL' AS product_type, 'TOPS' AS category_summary, 'SHIRT' AS category, 'fulfillment' AS calc_type, 'Exclude orders cancelled in paydate & EC-fulfilled from O2O unfulfilled' AS fulfillment_calc_type, 'RMB' AS currency, 48 AS o2o_fulfillment_request_failed_times, 565 AS o2o_fulfillment_request_times, 418.70 AS o2o_fulfillment_request_duration, 322 AS o2o_fulfillment_request_sku_qty
UNION ALL
SELECT '2026-07-28 10:00:00' AS etl_time, '2025/7/20' AS dt, 'day' AS data_type, '2025-07-20' AS data_date, '30' AS data_week, 'FW202530' AS data_week_name, '07_Oct' AS data_month, '2025财年7月' AS data_month_name, '3' AS data_quarter, '2025财年第三季度' AS data_quarter_name, '2025' AS data_year, '2025财年' AS data_year_name, 'TM' AS framework, 'MN' AS gender, 'RALPH' AS brand, 'ACCESSORIES' AS product_type, 'BOTTOMS' AS category_summary, 'PANT' AS category, 'payment' AS calc_type, 'Exclude orders cancelled in pay date' AS fulfillment_calc_type, 'RMB' AS currency, 50 AS o2o_fulfillment_request_failed_times, 595 AS o2o_fulfillment_request_times, 438.50 AS o2o_fulfillment_request_duration, 338 AS o2o_fulfillment_request_sku_qty
UNION ALL
SELECT '2026-07-28 10:00:00' AS etl_time, '2025/7/20' AS dt, 'day' AS data_type, '2025-07-20' AS data_date, '30' AS data_week, 'FW202530' AS data_week_name, '07_Oct' AS data_month, '2025财年7月' AS data_month_name, '3' AS data_quarter, '2025财年第三季度' AS data_quarter_name, '2025' AS data_year, '2025财年' AS data_year_name, 'JD' AS framework, 'CW' AS gender, 'LAUREN' AS brand, 'FOOTWEAR' AS product_type, 'OUTERWEAR' AS category_summary, 'JACKET' AS category, 'payment' AS calc_type, 'Exclude orders cancelled in paydate & EC-fulfilled from O2O unfulfilled' AS fulfillment_calc_type, 'RMB' AS currency, 52 AS o2o_fulfillment_request_failed_times, 625 AS o2o_fulfillment_request_times, 458.30 AS o2o_fulfillment_request_duration, 355 AS o2o_fulfillment_request_sku_qty
UNION ALL
SELECT '2026-07-28 10:00:00' AS etl_time, '2025/6/15' AS dt, 'day' AS data_type, '2025-06-15' AS data_date, '25' AS data_week, 'FW202525' AS data_week_name, '06_Sep' AS data_month, '2025财年6月' AS data_month_name, '3' AS data_quarter, '2025财年第三季度' AS data_quarter_name, '2025' AS data_year, '2025财年' AS data_year_name, 'TM' AS framework, 'WM' AS gender, 'POLO' AS brand, 'APPAREL' AS product_type, 'TOPS' AS category_summary, 'DRESS' AS category, 'fulfillment' AS calc_type, 'Exclude orders cancelled in pay date' AS fulfillment_calc_type, 'RMB' AS currency, 55 AS o2o_fulfillment_request_failed_times, 655 AS o2o_fulfillment_request_times, 478.60 AS o2o_fulfillment_request_duration, 372 AS o2o_fulfillment_request_sku_qty
UNION ALL
SELECT '2026-07-28 10:00:00' AS etl_time, '2025/6/15' AS dt, 'day' AS data_type, '2025-06-15' AS data_date, '25' AS data_week, 'FW202525' AS data_week_name, '06_Sep' AS data_month, '2025财年6月' AS data_month_name, '3' AS data_quarter, '2025财年第三季度' AS data_quarter_name, '2025' AS data_year, '2025财年' AS data_year_name, 'JD' AS framework, 'WM' AS gender, 'RALPH' AS brand, 'ACCESSORIES' AS product_type, 'BOTTOMS' AS category_summary, 'COAT' AS category, 'fulfillment' AS calc_type, 'Exclude orders cancelled in paydate & EC-fulfilled from O2O unfulfilled' AS fulfillment_calc_type, 'RMB' AS currency, 58 AS o2o_fulfillment_request_failed_times, 685 AS o2o_fulfillment_request_times, 498.20 AS o2o_fulfillment_request_duration, 388 AS o2o_fulfillment_request_sku_qty
UNION ALL
SELECT '2026-07-28 10:00:00' AS etl_time, '2025/6/15' AS dt, 'day' AS data_type, '2025-06-15' AS data_date, '25' AS data_week, 'FW202525' AS data_week_name, '06_Sep' AS data_month, '2025财年6月' AS data_month_name, '3' AS data_quarter, '2025财年第三季度' AS data_quarter_name, '2025' AS data_year, '2025财年' AS data_year_name, 'RLE' AS framework, 'MN' AS gender, 'LAUREN' AS brand, 'FOOTWEAR' AS product_type, 'OUTERWEAR' AS category_summary, 'SHIRT' AS category, 'payment' AS calc_type, 'Exclude orders cancelled in pay date' AS fulfillment_calc_type, 'RMB' AS currency, 60 AS o2o_fulfillment_request_failed_times, 715 AS o2o_fulfillment_request_times, 518.40 AS o2o_fulfillment_request_duration, 405 AS o2o_fulfillment_request_sku_qty
UNION ALL
SELECT '2026-07-28 10:00:00' AS etl_time, '2025/6/20' AS dt, 'day' AS data_type, '2025-06-20' AS data_date, '25' AS data_week, 'FW202525' AS data_week_name, '06_Sep' AS data_month, '2025财年6月' AS data_month_name, '3' AS data_quarter, '2025财年第三季度' AS data_quarter_name, '2025' AS data_year, '2025财年' AS data_year_name, 'JD' AS framework, 'CW' AS gender, 'POLO' AS brand, 'APPAREL' AS product_type, 'TOPS' AS category_summary, 'PANT' AS category, 'payment' AS calc_type, 'Exclude orders cancelled in paydate & EC-fulfilled from O2O unfulfilled' AS fulfillment_calc_type, 'RMB' AS currency, 62 AS o2o_fulfillment_request_failed_times, 745 AS o2o_fulfillment_request_times, 538.70 AS o2o_fulfillment_request_duration, 422 AS o2o_fulfillment_request_sku_qty
UNION ALL
SELECT '2026-07-28 10:00:00' AS etl_time, '2025/6/20' AS dt, 'day' AS data_type, '2025-06-20' AS data_date, '25' AS data_week, 'FW202525' AS data_week_name, '06_Sep' AS data_month, '2025财年6月' AS data_month_name, '3' AS data_quarter, '2025财年第三季度' AS data_quarter_name, '2025' AS data_year, '2025财年' AS data_year_name, 'RLE' AS framework, 'WM' AS gender, 'RALPH' AS brand, 'ACCESSORIES' AS product_type, 'BOTTOMS' AS category_summary, 'JACKET' AS category, 'fulfillment' AS calc_type, 'Exclude orders cancelled in pay date' AS fulfillment_calc_type, 'RMB' AS currency, 65 AS o2o_fulfillment_request_failed_times, 775 AS o2o_fulfillment_request_times, 558.90 AS o2o_fulfillment_request_duration, 438 AS o2o_fulfillment_request_sku_qty
UNION ALL
SELECT '2026-07-28 10:00:00' AS etl_time, '2025/6/20' AS dt, 'day' AS data_type, '2025-06-20' AS data_date, '25' AS data_week, 'FW202525' AS data_week_name, '06_Sep' AS data_month, '2025财年6月' AS data_month_name, '3' AS data_quarter, '2025财年第三季度' AS data_quarter_name, '2025' AS data_year, '2025财年' AS data_year_name, 'DY' AS framework, 'WM' AS gender, 'LAUREN' AS brand, 'FOOTWEAR' AS product_type, 'OUTERWEAR' AS category_summary, 'DRESS' AS category, 'fulfillment' AS calc_type, 'Exclude orders cancelled in paydate & EC-fulfilled from O2O unfulfilled' AS fulfillment_calc_type, 'RMB' AS currency, 68 AS o2o_fulfillment_request_failed_times, 805 AS o2o_fulfillment_request_times, 579.30 AS o2o_fulfillment_request_duration, 455 AS o2o_fulfillment_request_sku_qty
UNION ALL
SELECT '2026-07-28 10:00:00' AS etl_time, '2025/6/20' AS dt, 'day' AS data_type, '2025-06-20' AS data_date, '25' AS data_week, 'FW202525' AS data_week_name, '06_Sep' AS data_month, '2025财年6月' AS data_month_name, '3' AS data_quarter, '2025财年第三季度' AS data_quarter_name, '2025' AS data_year, '2025财年' AS data_year_name, 'TM' AS framework, 'CW' AS gender, 'POLO' AS brand, 'APPAREL' AS product_type, 'TOPS' AS category_summary, 'COAT' AS category, 'payment' AS calc_type, 'Exclude orders cancelled in pay date' AS fulfillment_calc_type, 'RMB' AS currency, 70 AS o2o_fulfillment_request_failed_times, 835 AS o2o_fulfillment_request_times, 599.50 AS o2o_fulfillment_request_duration, 472 AS o2o_fulfillment_request_sku_qty;
    "),
    更改的类型 = Table.TransformColumnTypes(源,{{"data_date", type date}})
in
    更改的类型