let
    源 = Odbc.Query("dsn=bytehouse_rl", 
    "
SELECT
    `etl_time`,
    `user_id`                AS `user_id_origin`,
    MD5(`user_id`)           AS `user_id`,
    `user_name`,
    `customer_id`,
    `member_id`,
    `mobile`,
    `customer_tier`,
    `gender`,
    `is_employee`,
    `platform`,
    `shop_info_id`,
    `shop_id`,
    `shop_name`,
    `shop_name_en`,
    `shop_code`,
    `create_date`,
    `create_time`,
    `register_date`,
    `register_time`,
    `first_login_channel`,
    `last_login_channel`,
    `first_pay_date`,
    `last_pay_date`,
    `nearly_7_pay_amt`,
    `nearly_7_order_cnt`,
    `nearly_7_pay_qty`,
    `nearly_15_pay_amt`,
    `nearly_15_order_cnt`,
    `nearly_15_pay_qty`,
    `nearly_30_pay_amt`,
    `nearly_30_order_cnt`,
    `nearly_30_pay_qty`,
    `nearly_60_pay_amt`,
    `nearly_60_order_cnt`,
    `nearly_60_pay_qty`,
    `nearly_90_pay_amt`,
    `nearly_90_order_cnt`,
    `nearly_90_pay_qty`,
    `nearly_180_pay_amt`,
    `nearly_180_order_cnt`,
    `nearly_180_pay_qty`,
    `nearly_365_pay_amt`,
    `nearly_365_order_cnt`,
    `nearly_365_pay_qty`,
    `total_pay_amt`,
    `total_pay_order_cnt`,
    `total_pay_qty`,
    `total_return_amt`,
    `total_return_order_cnt`,
    `total_return_qty`,
    `total_cancel_amt`,
    `total_cancel_order_cnt`,
    `total_cancel_qty`
FROM `indep_rl_dw`.`t05_customer_info`

    "),
    更改的类型 = Table.TransformColumnTypes(源,{{"register_date", type date}})
in
    更改的类型